### ISSUE TITLE
tls.createSecurePair is being runtime-deprecated

### ISSUE THREAD

**Issue by ChALkeR** [andris9/rai#11]
Ref: https://github.com/nodejs/node/pull/11349

Used in:
```
rai-0.1.12.tgz/lib/mockup.js:75:                pair = tlslib.createSecurePair(sslcontext, false);
rai-0.1.12.tgz/lib/starttls.js:40:    pair = require('tls').createSecurePair(sslcontext, true);
```

See also https://github.com/andris9/rai/issues/8.
See e.g. https://github.com/sidorares/node-mysql2/pull/367 for a feature detection example.

**Comment by andris9** [comment]
*rai* module is deprecated as well, it only exists to support the code written for old versions of Node.js.

**Comment by ChALkeR** [comment]
@andris9 Perhaps it should be documented as deprecated, then (i.e. in the Readme and/or via `npm deprecate`)? Atm, https://www.npmjs.com/package/rai has 137043 downloads per month, which is pretty significant.

**Comment by ChALkeR** [comment]
It looks like most downloads come from https://www.npmjs.com/package/simplesmtp, which is documented to be deprecated in the Readme, but has a lot of dependents. Most likely it's worth `npm deprecate`-ing that module, too (which it isn't now).
